# Numpy Excercise:

In [169]:
import numpy as np

In [170]:
#Print the numpy version and the configuration 
print(np.__version__)
np.show_config()

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/programs1/python datamining1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/programs1/python datamining1\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/programs1/python datamining1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/programs1/python datamining1\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/programs1/python datamining1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/programs1/python datamining1\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/programs1/python datamining1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['E:/programs1/python datamining1\\Library\

In [171]:
#Create a null vector of size 15
Z = np.zeros(15)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [172]:
#Create a null vector of size 30 but the nineteen value which is 1 
Z = np.zeros(30)
Z[19] = 1
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [173]:
#Create a vector with values ranging from 24 to 76
Z = np.arange(24,77)
print(Z)

[24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76]


In [174]:
#7. Reverse a vector (first element becomes last)
Z = np.arange(77)
z = Z[::-1]

In [175]:
z

array([76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,
       59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1,  0])

In [176]:
# Create a 4x4 matrix with values ranging from 10 to 25
Z = np.arange(16).reshape(4,4)
print(Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [177]:
#Find indices of non­zero elements from [1,2,0,0,5,0,6,0,0,2,8,4,0]
nz = np.nonzero([1,2,0,0,5,0,6,0,0,2,8,4,0])
print(nz)

(array([ 0,  1,  4,  6,  9, 10, 11], dtype=int64),)


In [178]:
#Create a 7x7 identity matrix
Z =np.eye(7)
print(Z)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [179]:
#Create a 5x5x5 array with random values
Z = np.random.random((5,5,5))
print(Z)

[[[0.48363598 0.61254371 0.34624266 0.96512671 0.82870958]
  [0.0608595  0.96894796 0.09615466 0.7307277  0.50324127]
  [0.81416884 0.06281598 0.60275588 0.83541887 0.66130695]
  [0.82979568 0.76277417 0.14288286 0.26313772 0.92087896]
  [0.02137434 0.78524946 0.69590325 0.88274277 0.60406055]]

 [[0.23616871 0.5493972  0.44641239 0.48622165 0.3684864 ]
  [0.21057121 0.82925099 0.79172354 0.02671955 0.88831195]
  [0.15021187 0.99445745 0.5440574  0.86322906 0.62659328]
  [0.59710673 0.16544485 0.73583116 0.89599505 0.15528696]
  [0.0028052  0.02657705 0.12094095 0.73645529 0.66639335]]

 [[0.76091567 0.8189314  0.17510336 0.89462423 0.22118535]
  [0.39437745 0.36063842 0.07558409 0.22847875 0.01576482]
  [0.27993298 0.55164717 0.56501331 0.28065746 0.04498455]
  [0.216995   0.3814604  0.82144221 0.45902976 0.36183492]
  [0.88066907 0.56286725 0.85904546 0.20933862 0.02345375]]

 [[0.24617497 0.62164035 0.19439077 0.82654966 0.47509589]
  [0.23510801 0.96495012 0.49966079 0.19988513 0.7

In [180]:
#Create a 12x10 array with random values and find the minimum and maximum
#values
Z = np.random.random((12,10))
Zmin,Zmax = Z.min(),Z.max()
print(Zmin, Zmax)

0.004528468781489048 0.9845342735085428


In [181]:
#Create a random vector of size 42 and and find the mean value
Z = np.random.random(42)
m = Z.mean()
print(m)

0.4620529405423978


In [182]:
#Create a 2d array with 1 on the border and 0 inside (
Z = np.ones((8,8))
Z[1:-1,1:-1] = 0 

In [183]:
Z

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [184]:
#What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [185]:
0 * np.nan

nan

In [186]:
np.nan == np.nan

False

In [187]:
np.inf > np.nan

False

In [188]:
np.nan - np.nan

nan

In [189]:
0.3 == 3 * 0.1

False

In [190]:
# Create a 6x6 matrix with values 1,2,3,4,5 just below the diagonal
Z = np.diag(1+np.arange(5), k= -1)
print(Z)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [191]:
Z = np.diag(3+np.arange(5), k= -1)
print(Z)

[[0 0 0 0 0 0]
 [3 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 6 0 0]
 [0 0 0 0 7 0]]


In [192]:
Z = np.diag(3+np.arange(5), k= -2)
print(Z)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 5 0 0 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 7 0 0]]


In [193]:
#Create a 10x10 matrix and fill it with a checkerboard pattern
Z = np.zeros((10,10), dtype= int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [194]:
# Consider a (4,5,6,7) shape array, what is the index (w,x,y,z) of the 170th element?
print(np.unravel_index(170,(4,5,6,7)))

(0, 4, 0, 2)


In [195]:
#Create a checkerboard 10x10 matrix using the tile function
Z = np.tile(np.array([[0,1],[1,0]]),(5,5))
print(Z)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [196]:
Z = np.tile(np.array([[0,1],[1,0]]),(6,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [197]:
Z = np.tile(np.array([[0,1],[1,0]]),(5,6))
print(Z)

[[0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]]


In [198]:
# Normalize a 7x7 random matrix 
Z =  np.random.random((7,7))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.07077935 0.09333652 0.46220305 0.33271287 0.54179019 0.68428226
  0.8519833 ]
 [0.15946373 1.         0.2483688  0.89025977 0.57861179 0.81722633
  0.28537446]
 [0.55458742 0.95083718 0.32140401 0.23109641 0.29677641 0.17478929
  0.74060839]
 [0.10430315 0.31030024 0.85334288 0.86035753 0.40996844 0.74518182
  0.93269867]
 [0.         0.6889664  0.90733495 0.94753903 0.30900489 0.25558375
  0.70836716]
 [0.43993786 0.72500148 0.20227245 0.47591492 0.32151674 0.96023634
  0.13161898]
 [0.01324223 0.54359637 0.16016323 0.11964438 0.0439205  0.49433874
  0.55307225]]


In [199]:
#Create a custom dtype that describes a color as four unisgned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte,  1),
                 ("b", np.ubyte,  1),
                 ("a", np.ubyte,  1)])
  

C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/696051920.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [200]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [201]:
#. Multiply a 6x4 matrix by a 4x2 matrix (real matrix product)
Z = np.dot(np.ones((6,4)), np.ones((4,2)))
print(Z)

[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


In [202]:
#Given a 1D array, negate all elements which are between 5 and 9, in place.
Z = np.arange(14)
Z[(5<Z) & (Z<=9)] *=-1

In [203]:
Z

array([ 0,  1,  2,  3,  4,  5, -6, -7, -8, -9, 10, 11, 12, 13])

In [204]:
#What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: 'numpy.ndarray' object is not callable

In [206]:
2 << Z >> 2


array([   0,    1,    2,    4,    8,   16,    0,    0,    0,    0,  512,
       1024, 2048, 4096], dtype=int32)

In [207]:
Z <- Z

array([False, False, False, False, False, False,  True,  True,  True,
        True, False, False, False, False])

In [208]:
1j*Z

array([ 0. +0.j,  0. +1.j,  0. +2.j,  0. +3.j,  0. +4.j,  0. +5.j,
       -0. -6.j, -0. -7.j, -0. -8.j, -0. -9.j,  0.+10.j,  0.+11.j,
        0.+12.j,  0.+13.j])

In [209]:
Z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5., -6., -7., -8., -9., 10., 11., 12.,
       13.])

In [210]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [211]:
#What are the result of the following expressions?
np.array(0) // np.array(0)
np.array(0) // np.array(0.)
np.array(0) / np.array(0)
np.array(0) / np.array(0.)

C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/3375619940.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/3375619940.py:3: RuntimeWarning: invalid value encountered in floor_divide
  np.array(0) // np.array(0.)
C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/3375619940.py:4: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/3375619940.py:5: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0.)


nan

In [212]:
np.array(0) // np.array(0)

C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [213]:
#How to round away from zero a float array ? 
Z = np.random.uniform(-20,+20,20)
print(np.trunc(Z + np.copysign(0.5,Z)))

[ -9.  -3.  19.  -8.  12. -12.   6. -12.  -6.  -3.   9.  -5.   9.   8.
 -14.  20.   6. -10.  11. -16.]


In [214]:
#Extract the integer part of a random array using 5 different methods 
Z = np.random.uniform(0,15,15)
print(Z -Z%1)

[14.  8.  7. 10. 12. 13. 10. 14.  5. 12.  5.  8.  7.  1.  5.]


In [215]:
print(np.floor(Z))

[14.  8.  7. 10. 12. 13. 10. 14.  5. 12.  5.  8.  7.  1.  5.]


In [216]:
print(np.ceil(Z)-1)

[14.  8.  7. 10. 12. 13. 10. 14.  5. 12.  5.  8.  7.  1.  5.]


In [217]:
print(Z.astype(int))

[14  8  7 10 12 13 10 14  5 12  5  8  7  1  5]


In [218]:
print(np.trunc(Z))

[14.  8.  7. 10. 12. 13. 10. 14.  5. 12.  5.  8.  7.  1.  5.]


In [219]:
#. Create a 8x8 matrix with row values ranging from 0 to 7
Z = np.zeros((8,8))
Z += np.arange(8)
print(Z)

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]]


In [220]:
#. Consider a generator function that generates 20 integers and use it to build an
#array
def generate():
    for x in range(20):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [221]:
def generate():
    for x in range(20):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [222]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded 
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [223]:
Z = np.linspace(0,1,22,endpoint=True)[1:-1]    #size 20
print(Z)

[0.04761905 0.0952381  0.14285714 0.19047619 0.23809524 0.28571429
 0.33333333 0.38095238 0.42857143 0.47619048 0.52380952 0.57142857
 0.61904762 0.66666667 0.71428571 0.76190476 0.80952381 0.85714286
 0.9047619  0.95238095]


In [224]:
Z = np.linspace(0,1,10,endpoint=True)[1:-1]#size 8
print(Z)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


In [225]:
#Create a random vector of size 15 and sort it
Z = np.random.random(15)
Z.sort()
print(Z)

[0.02116318 0.02516788 0.13004663 0.16773114 0.18996445 0.19661984
 0.31880289 0.39408705 0.39899334 0.4225463  0.65185293 0.71074933
 0.71808089 0.72843709 0.85659455]


In [226]:
#How to sum a small array faster than np.sum?
Z = np.arange(20)
np.add.reduce(Z)

190

In [227]:
#Consider two random array A anb B, check if they are equal


In [228]:
A = np.random.randint(2,4,8)
B = np.random.randint(2,4,8)
equal = np.allclose(A,B)
print(equal)

False


In [229]:
A = np.random.randint(4,5,6)
B = np.random.randint(4,5,6)
equal = np.allclose(A,B)
print(equal)

True


In [230]:
A = np.random.randint(1,2,8)
B = np.random.randint(2,4,8)
equal = np.allclose(A,B)
print(equal)

False


In [231]:
# Make an array immutable (read­only)
Z = np.zeros(25)
Z.flags.writeable = False
z[0] = 1

In [232]:
#Consider a random 10x2 matrix representing cartesian coordinates, convert them
#to polar coordinates
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.08819815 1.09908315 0.72764512 0.6240751  1.19825037 0.8090215
 0.82228144 0.55287784 0.85727014 0.50945139]
[0.59326997 0.48648585 0.38075703 0.77663811 0.82778437 0.24054672
 0.02761445 0.81154201 0.49975772 0.61126264]


In [233]:
Z = np.random.random((8,2))#8x2 matrix
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.16123575 0.96812486 1.13181539 0.60251097 0.7146606  1.03149492
 0.81476475 0.90543615]
[0.99548141 0.89722679 0.83898331 0.89880079 0.81202745 0.97873235
 1.27902267 1.37090232]


In [234]:
#Create random vector of size 20 and replace the maximum value by 0
Z = np.random.random(20)
Z[Z.argmax()] = 0
print(Z)

[0.39086153 0.60332571 0.20190268 0.29153501 0.58664997 0.13970058
 0.04849527 0.7264139  0.44332723 0.27939635 0.27311811 0.44679655
 0.43874373 0.1070746  0.         0.40249765 0.4109487  0.88576324
 0.81589918 0.82575288]


In [235]:
#Create a structured array with xand ycoordinates covering the [0,1]x[0,1] area
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [236]:
Z = np.zeros((7,7),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,7),np.linspace(0,1,7))
print(Z)

[[(0.        , 0.        ) (0.16666667, 0.        )
  (0.33333333, 0.        ) (0.5       , 0.        )
  (0.66666667, 0.        ) (0.83333333, 0.        )
  (1.        , 0.        )]
 [(0.        , 0.16666667) (0.16666667, 0.16666667)
  (0.33333333, 0.16666667) (0.5       , 0.16666667)
  (0.66666667, 0.16666667) (0.83333333, 0.16666667)
  (1.        , 0.16666667)]
 [(0.        , 0.33333333) (0.16666667, 0.33333333)
  (0.33333333, 0.33333333) (0.5       , 0.33333333)
  (0.66666667, 0.33333333) (0.83333333, 0.33333333)
  (1.        , 0.33333333)]
 [(0.        , 0.5       ) (0.16666667, 0.5       )
  (0.33333333, 0.5       ) (0.5       , 0.5       )
  (0.66666667, 0.5       ) (0.83333333, 0.5       )
  (1.        , 0.5       )]
 [(0.        , 0.66666667) (0.16666667, 0.66666667)
  (0.33333333, 0.66666667) (0.5       , 0.66666667)
  (0.66666667, 0.66666667) (0.83333333, 0.66666667)
  (1.        , 0.66666667)]
 [(0.        , 0.83333333) (0.16666667, 0.83333333)
  (0.33333333, 0.83333333) (

In [237]:
#Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi ­ yj))
X = np.arange(10)
Y =  X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

33961.93294480225


In [238]:
X = np.arange(4)
Y =  X + 0.8
C = 1.0 / np.subtract.outer(X,Y)
print(C)

[[-1.25       -0.55555556 -0.35714286 -0.26315789]
 [ 5.         -1.25       -0.55555556 -0.35714286]
 [ 0.83333333  5.         -1.25       -0.55555556]
 [ 0.45454545  0.83333333  5.         -1.25      ]]


In [239]:
X = np.arange(4)
Y =  X + 0.8
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

79.83810305437386


In [240]:
#Print the minimum and maximum representable value for each numpy scalar type
for dtype in[np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in[np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [241]:
#. How to print all the values of an array?
#np.set_printoptions(threshold=np.nan)
#Z = np.zeros((7,7))
#print(Z)

In [242]:
# How to find the closest value (to a given scalar) in an array?
Z = np.arange(200)
v = np.random.uniform(0,200)
index = (np.abs(Z-v)).argmin()
print(Z[index])

136


In [243]:
Z = np.arange(200)
v = np.random.uniform(7,200)
index = (np.abs(Z-v)).argmin()
print(Z[index])

30


In [244]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

29


In [245]:
#. Create a structured array representing a position (x,y) and a color (r,g,b) 
Z = np.zeros(15, [('Position',[('x',float,1),
                               ('y',float,1)]),
                 ('Color',    [('r',float,1),
                               ('g',float,1),
                               ('b',float,1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/329857141.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(15, [('Position',[('x',float,1),


In [246]:
Z = np.zeros(10, [('Position',[('x',float,1),
                               ('y',float,1)]),
                 ('Color',    [('r',float,1),
                               ('g',float,1),
                               ('b',float,1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/1085554366.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('Position',[('x',float,1),


In [247]:
#Consider a random vector with shape (100,2) representing coordinates, find point
#by point distances 
import scipy.spatial
Z = np.random.random((10,2))
#X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:1])
#D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
#print(D)

#Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.72340762 0.10255435 0.72668328 0.86665641 0.70506056
  0.87209899 0.20105902 0.49605209 0.15650946]
 [0.72340762 0.         0.82312259 0.25616169 0.358683   0.75598338
  0.29779156 0.53789553 0.2419186  0.69578568]
 [0.10255435 0.82312259 0.         0.8287589  0.96794245 0.77564546
  0.97439951 0.30336015 0.59805668 0.18994676]
 [0.72668328 0.25616169 0.8287589  0.         0.1486866  0.53142491
  0.14721885 0.52566388 0.26476957 0.7539715 ]
 [0.86665641 0.358683   0.96794245 0.1486866  0.         0.55763473
  0.08019377 0.66643607 0.41338665 0.90089827]
 [0.70506056 0.75598338 0.77564546 0.53142491 0.55763473 0.
  0.62536438 0.57909684 0.59313093 0.82732149]
 [0.87209899 0.29779156 0.97439951 0.14721885 0.08019377 0.62536438
  0.         0.67105869 0.39583353 0.89234515]
 [0.20105902 0.53789553 0.30336015 0.52566388 0.66643607 0.57909684
  0.67105869 0.         0.30166662 0.26126825]
 [0.49605209 0.2419186  0.59805668 0.26476957 0.41338665 0.59313093
  0.39583353 0.30166

In [248]:
#How to convert a float (32 bits) array into an integer (32 bits) in place?
Z =np.arange(20, dtype=np.int32)
Z = Z.astype(np.float32, copy = False)

In [249]:
Z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [250]:
Z =np.arange(30, dtype=np.float32)
Z = Z.astype(np.int32, copy = False)

In [251]:
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [252]:
Z =np.arange(20, dtype=np.int32)
Z = Z.astype(np.float32, copy = True)

In [253]:
Z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [254]:
Z =np.arange(30, dtype=np.float32)
Z = Z.astype(np.int32, copy = True)

In [255]:
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [256]:
## How to read the following file?
# -------------
1,2,3,4,5
6,,7,8
,,9,10,11
# -------------
Z = np.genfromtxt("missing.dat", delimiter=",")

SyntaxError: invalid syntax (Temp/ipykernel_5632/903541521.py, line 4)

In [257]:
#What is the equivalent of enumerate for numpy arrays?
Z = np.arange(16).reshape(4,4)
for index, value in np.ndenumerate(Z):
    print(index,value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11
(3, 0) 12
(3, 1) 13
(3, 2) 14
(3, 3) 15


In [258]:
#ndenumerate:
#Multidimensional index iterator.
#Return an iterator yielding pairs of array coordinates and values.
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [259]:
#numpy.ndindex
#class numpy.ndindex(*shape)[source]
#An N-dimensional iterator object to index arrays.
for index in np.ndindex(3, 2, 1):
    print(index)

(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)


In [260]:
#Generate a generic 2D Gaussian­like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [261]:
#numpy.meshgrid
#Return coordinate matrices from coordinate vectors.

#Make N-D coordinate arrays for vectorized evaluations of N-D scalar/vector fields over N-D grids, given one-dimensional coordinate arrays x1, x2,…, xn.

In [262]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [263]:
#numpy.linspace
#Return evenly spaced numbers over a specified interval
np.linspace(3.0, 5.0, num=10)

array([3.        , 3.22222222, 3.44444444, 3.66666667, 3.88888889,
       4.11111111, 4.33333333, 4.55555556, 4.77777778, 5.        ])

In [264]:
#How to randomly place p elements in a 2D array? 
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)

In [265]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [266]:
#Subtract the mean of each row of a matrix 
X = np.random.rand(6,18)
Y = X - X.mean(axis =1 , keepdims=True)##numpy new version

In [267]:
Y

array([[ 0.18104612,  0.19245752,  0.04765247, -0.38437602,  0.15146975,
        -0.23924205,  0.36236068,  0.13075874, -0.09040188, -0.22600651,
        -0.29121782,  0.03510801,  0.12877467,  0.23648418,  0.08262973,
        -0.18131424,  0.15284657, -0.28902992],
       [-0.40439702, -0.36233472, -0.3544918 , -0.04047684, -0.45776567,
        -0.35102748, -0.0586001 ,  0.31093809,  0.11074917,  0.30558316,
        -0.17979254,  0.4092949 , -0.03662978,  0.05249915,  0.03643984,
         0.30893882,  0.38390196,  0.32717086],
       [-0.58274366,  0.25451679, -0.38997736,  0.36241875, -0.31713007,
         0.23914402,  0.18386148,  0.15987607, -0.12295976,  0.33768106,
         0.1483492 , -0.09208479, -0.36282507,  0.11603291, -0.2249016 ,
         0.32868447,  0.2542965 , -0.29223896],
       [ 0.34419414,  0.33522302, -0.18145135,  0.13218476,  0.20146676,
         0.1312628 , -0.00937919,  0.03647384, -0.09815817, -0.39861129,
        -0.33939524,  0.28796226,  0.24745311, -0.564

In [268]:
#numpy older version:
X = np.random.rand(6,18)
Y = X - X.mean(axis =1).reshape(-1,1)## Numpy older version

In [269]:
Y

array([[ 0.36111617,  0.1206474 , -0.28584437, -0.0697199 , -0.07498076,
         0.31514167, -0.51547469,  0.23248985,  0.08586888,  0.27822483,
        -0.10366229,  0.19775487,  0.19577972,  0.40492293, -0.47242471,
        -0.25805087, -0.11279439, -0.29899435],
       [-0.05078664,  0.29014368, -0.26800598,  0.24566379, -0.32673166,
         0.40213131, -0.42430297,  0.02284597,  0.49218726,  0.52401496,
         0.1352427 , -0.22335133, -0.42182473,  0.18914175,  0.05758579,
        -0.43896929, -0.3616895 ,  0.15670487],
       [-0.35887014,  0.08503673,  0.20526155, -0.11329824,  0.30514014,
        -0.34304464,  0.18832145, -0.25943006, -0.22561118,  0.13665636,
         0.19425811, -0.40709171,  0.12699866,  0.09305249,  0.08014333,
         0.15432376,  0.49604608, -0.35789271],
       [ 0.09452128,  0.29090831,  0.30826768, -0.11255317,  0.19153321,
        -0.5323362 ,  0.12927455, -0.50383657,  0.03032855, -0.20030794,
        -0.14916687,  0.25685875, -0.16892972,  0.292

In [270]:
#How to I sort an array by the nth column?
Z = np.random.randint(0,15,(4,4))
print(Z)
print(Z[Z[:,1].argsort()])

[[ 6 14  4 12]
 [ 8  3  7  2]
 [ 4  5  7  4]
 [ 9  2 13  8]]
[[ 9  2 13  8]
 [ 8  3  7  2]
 [ 4  5  7  4]
 [ 6 14  4 12]]


In [271]:
#argsort:
#Returns the indices that would sort an array
# one dimensional:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [272]:
# Two dimensional:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)
ind

array([1, 2, 0], dtype=int64)

In [273]:
np.take_along_axis(x, ind, axis=0)  # same as np.sort(x, axis=0)

array([1, 2, 3])

In [274]:
#Indices of the sorted elements of a N-dimensional array:
ind = np.unravel_index(np.argsort(x, axis=None), x.shape)
ind

(array([1, 2, 0], dtype=int64),)

In [275]:
x[ind]  # same as np.sort(x, axis=None)

array([1, 2, 3])

In [276]:
#How to tell if a given 2D array has null columns?
Z = np.random.randint(0,6,(6,15))
print((~Z.any(axis=0)).any())

False


In [277]:
#Find the nearest value from a given value in an array:
Z = np.random.uniform(0,2,15)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

0.26597705959665086


In [278]:
#Create an array class that has a name attribute 
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
    

In [279]:
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [280]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="Rakib"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "Rakib")
    

In [281]:
Z = NamedArray(np.arange(15), "range_15")
print (Z.name)

range_15


In [282]:
#. Consider a given vector, how to add 1 to each element indexed by a second
#vector (be careful with repeated indices)?
Z = np.ones(20)
I = np.random.randint(0,len(Z),40)
Z+= np.bincount(I, minlength= len(Z))
print(Z)

[1. 6. 4. 2. 2. 2. 2. 3. 3. 2. 4. 6. 2. 2. 4. 3. 3. 1. 4. 4.]


In [283]:
# How to accumulate elements of a vector (X) to an array (F) based on an index list
#(I)?
X = [1,2,3,5,6,8,12,15]
I = [2,4,5,9,2,3,5,10]
F = np.bincount(I,X)
print(F)

[ 0.  0.  7.  8.  2. 15.  0.  0.  0.  5. 15.]


In [284]:
#Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique
#colors
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [285]:
w,h = 12,12
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*144*144 + I[...,1]*144 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [286]:
# Considering a four dimensions array, how to get sum over the last two axis at
#once?
A = np.random.randint(0,15,(5,8,5,8))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[270 255 298 227 243 310 344 291]
 [256 315 278 270 262 308 251 234]
 [295 254 257 293 268 291 288 308]
 [274 292 321 214 296 274 271 343]
 [296 296 288 276 269 307 285 277]]


In [287]:
# Considering a one­dimensional vector D, how to compute means of subsets of D
#using a vector S of same size describing subset indices?
D = np.random.uniform(0,5,150)
S = np. random.randint(0,15,150)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means =  D_sums / D_counts
print(D_means)


[3.83639436 1.99764047 2.57226689 2.31024554 2.99464898 2.41681943
 1.76925279 2.50811409 3.11781383 2.79427884 3.07479539 2.51142764
 1.47470864 2.43874884 2.54959668]


In [288]:
D = np.random.uniform(0,1,150)
S = np. random.randint(0,15,150)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means =  D_sums / D_counts
print(D_means)

[0.47158002 0.38251845 0.60245176 0.83786779 0.42073626 0.47531667
 0.35870056 0.32549844 0.39233169 0.61782211 0.583925   0.59314224
 0.49814873 0.30833612 0.37961293]


In [289]:
print(D_sums)

[6.60212028 3.82518448 4.21716232 5.02720673 1.68294503 7.60506667
 2.15220338 2.92948598 2.35399012 9.26733166 7.59102499 5.93142244
 4.98148728 4.31670567 3.79612928]


In [290]:
print(D_sums)

[6.60212028 3.82518448 4.21716232 5.02720673 1.68294503 7.60506667
 2.15220338 2.92948598 2.35399012 9.26733166 7.59102499 5.93142244
 4.98148728 4.31670567 3.79612928]


In [292]:
# Fast version:
np.sum(A * B.T , axis=1)

array([[[ 90, 114, 152,  70,  62, 171, 128, 152],
        [148, 114, 162,  74, 132, 168,  98, 120],
        [176, 160, 120,  76, 134, 186,  42, 110],
        [ 92,  98,  78, 136, 120, 126, 134, 118],
        [138,  66, 122,  92, 108, 156, 114,  88]],

       [[122,  92, 100, 140, 148, 159, 106, 128],
        [102, 110,  90, 100, 116, 147, 110, 132],
        [122, 126,  88,  60,  84, 135,  90,  70],
        [102, 124, 112, 100, 140, 237, 128, 112],
        [104,  76,  88, 122,  92, 246,  94, 102]],

       [[132,  82,  92, 150,  92, 198, 132, 130],
        [ 74, 140, 142,  66, 152, 129, 114, 148],
        [130, 142, 102,  70,  86, 243,  98,  98],
        [100, 114,  60,  86, 112, 135, 126, 156],
        [ 82, 124, 102, 146, 114, 189, 126,  92]],

       [[ 98, 104, 124, 116, 112, 108, 100, 138],
        [144, 142, 192, 130,  98, 141, 126, 124],
        [122, 114, 126,  96,  96, 180,  74,  72],
        [114, 106,  82, 134, 134, 204, 108, 168],
        [132,  78, 106, 106, 118, 189, 118, 

In [293]:
# Faster version:
np.einsum("ij,ji->i", A, B)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

In [294]:
#Consider the vector [1, 2, 3, 4, 5, 6, 7, 8] how to build a new vector with 4 consecutive
#zeros interleaved between each value?
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8])
nz = 4
Z0 = np.zeros(len(Z) + (len(Z)-1) * (nz))
Z0[::nz+1]= Z
print(Z0)

[1. 0. 0. 0. 0. 2. 0. 0. 0. 0. 3. 0. 0. 0. 0. 4. 0. 0. 0. 0. 5. 0. 0. 0.
 0. 6. 0. 0. 0. 0. 7. 0. 0. 0. 0. 8.]


In [295]:
#. Consider an array of dimension (7,7,4), how to mulitply it by an array with
#dimensions (7,7)?
R = np.ones((7,7,4))
S = 2* np.ones((7,7))
print(R * S [:,:,None])


[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [296]:
R = np.ones((7,7,4))
S = 1* np.ones((7,7))
print(R * S [:,:,None])


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [297]:
#. How to swap two rows of an array?
X = np.arange(36).reshape(6,6)
X[[0,1]] = X[[1,0]]
print(X)

[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [298]:
#Consider a set of 10 triplets describing 10 triangles (with shared vertices), find
#the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 0, 11) ( 0, 61) ( 2, 45) ( 2, 54) ( 2, 80) ( 2, 86) (11, 61) (12, 49)
 (12, 62) (14, 49) (14, 92) (16, 49) (16, 94) (21, 41) (21, 65) (32, 41)
 (32, 50) (40, 89) (40, 95) (41, 50) (41, 65) (45, 55) (45, 85) (45, 86)
 (49, 62) (49, 92) (49, 94) (54, 80) (55, 85) (89, 95)]


In [299]:
# Given an array C that is a bincount, how to produce an array A such that
#np.bincount(A) == C?
C = np.bincount([1,2,2,3,4,5,5,7,7,8])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 2 2 3 4 5 5 7 7 8]


In [300]:
#How to compute averages using a sliding window over an array?
def moving_average(a, n=5) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(30)
print(moving_average(Z, n=5))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20. 21. 22. 23. 24. 25. 26. 27.]


In [301]:
def moving_average(a, n=6) :
    ret = np.cumsum(a, dtype=int)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(40)
print(moving_average(Z, n=6))

[ 2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5 15.5
 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5 24.5 25.5 26.5 27.5 28.5 29.5
 30.5 31.5 32.5 33.5 34.5 35.5 36.5]


In [302]:
#Consider a one­dimensional array Z, build a two­dimensional array whose first
#row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should
#be (Z[­3],Z[­2],Z[­1])
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)


In [303]:
a = np.arange(10)
a = a[::2]
Z = rolling(a, 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [304]:
a = np.arange(20)
a = a[::2]
Z = rolling(a, 4)
print(Z)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


In [305]:
#How to negate a boolean, or to change the sign of a float inplace?

Z = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

NameError: name 'arr' is not defined

In [306]:
import numpy as np
b = np.array([True, True, False, True, False])
b = np.invert(b)
print(b)

[False False  True False  True]


In [307]:
#Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to
#compute distance from p to each line i (P0[i],P1[i])? 
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.2918959  8.66855545 3.87983296 3.32208837 4.24948759 1.17231477
 0.11769545 1.80218336 2.19576242 8.27550865]


In [308]:
#70. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how
#to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[18.15689754  0.42729909  0.49495649 11.31113154  9.19535684 11.96652917
   3.9497406  14.05209178 15.82844106 12.03469685]
 [ 0.02214736  4.29215845 17.10036363  8.8635597  10.19399716  7.48782905
  16.2742463   0.41900569  1.81368797  6.95811197]
 [ 9.29372284  8.76309579 14.53892128  0.80980671  4.97516001  1.29677809
   9.57434571  9.79197091  2.55588968  2.05518261]
 [ 3.9419512   4.96617889  5.76579013  1.54910439  0.12998736  1.76510483
   7.14737945  0.22634095 13.23468313  1.94223534]
 [ 7.89544602  4.61310051 11.72912015  0.80557139  3.23145716  0.59821449
   8.62243947  7.08291831  5.90678763  1.07161752]
 [ 9.72027856  5.85811806  0.78697876  4.76014977  6.06084947  4.37251448
   0.89504747  4.69684204 17.36197086  4.07279093]
 [ 6.02510689  0.68850951  9.46633019  1.37026357  2.08334469  0.62924876
   8.2674397   4.06550094  8.76853402  0.41983784]
 [ 2.73921885  3.80852707 14.70017973  5.87431466  7.35843642  4.59023962
  13.2980285   2.49717566  3.8183992   4.12279703]


In [309]:
#Consider an arbitrary array, write a function that extract a subpart with a fixed
#shape and centered on a given element (pad with a fillvalue when necessary)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 4 6 6 3 3 3 9 0 5]
 [8 6 2 8 8 4 4 1 2 6]
 [5 4 9 7 0 1 3 8 3 6]
 [7 2 7 0 3 9 0 1 9 1]
 [0 0 2 8 3 7 7 1 1 8]
 [7 6 0 5 0 6 1 0 6 3]
 [4 0 3 9 9 2 8 2 5 0]
 [7 6 7 2 4 9 6 4 1 1]
 [2 7 2 9 7 1 9 1 0 5]
 [3 0 1 7 5 8 2 0 5 5]]
[[0 0 0 0 0]
 [0 3 4 6 6]
 [0 8 6 2 8]
 [0 5 4 9 7]
 [0 7 2 7 0]]


C:\Users\Rakib\AppData\Local\Temp/ipykernel_5632/4097660005.py:21: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [310]:
# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an
#array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
#from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [311]:
#Compute a matrix rank 
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)

In [312]:
print(rank)

10


In [313]:
#How to find the most frequent value in an array?
Z = np.random.randint(0,20,70)
print(np.bincount(Z).argmax())


2


In [314]:
# Extract all the contiguous 3x3 blocks from a random 10x10 matrix
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

In [315]:
print(C)

[[[[4 2 1]
   [2 1 1]
   [3 0 4]]

  [[2 1 4]
   [1 1 1]
   [0 4 0]]

  [[1 4 0]
   [1 1 0]
   [4 0 1]]

  [[4 0 1]
   [1 0 2]
   [0 1 3]]

  [[0 1 4]
   [0 2 1]
   [1 3 4]]

  [[1 4 1]
   [2 1 3]
   [3 4 2]]

  [[4 1 4]
   [1 3 1]
   [4 2 4]]

  [[1 4 0]
   [3 1 3]
   [2 4 1]]]


 [[[2 1 1]
   [3 0 4]
   [4 4 4]]

  [[1 1 1]
   [0 4 0]
   [4 4 1]]

  [[1 1 0]
   [4 0 1]
   [4 1 1]]

  [[1 0 2]
   [0 1 3]
   [1 1 2]]

  [[0 2 1]
   [1 3 4]
   [1 2 3]]

  [[2 1 3]
   [3 4 2]
   [2 3 2]]

  [[1 3 1]
   [4 2 4]
   [3 2 0]]

  [[3 1 3]
   [2 4 1]
   [2 0 3]]]


 [[[3 0 4]
   [4 4 4]
   [1 1 4]]

  [[0 4 0]
   [4 4 1]
   [1 4 1]]

  [[4 0 1]
   [4 1 1]
   [4 1 3]]

  [[0 1 3]
   [1 1 2]
   [1 3 4]]

  [[1 3 4]
   [1 2 3]
   [3 4 2]]

  [[3 4 2]
   [2 3 2]
   [4 2 1]]

  [[4 2 4]
   [3 2 0]
   [2 1 2]]

  [[2 4 1]
   [2 0 3]
   [1 2 4]]]


 [[[4 4 4]
   [1 1 4]
   [4 1 2]]

  [[4 4 1]
   [1 4 1]
   [1 2 4]]

  [[4 1 1]
   [4 1 3]
   [2 4 1]]

  [[1 1 2]
   [1 3 4]
   [4 1 4]]

  [[1 2 3]
   

In [316]:
# Create a 2D array subclass such that Z[i,j] == Z[j,i]
import numpy as np
class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


SyntaxError: invalid syntax (Temp/ipykernel_5632/1313352290.py, line 4)

In [317]:
#Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape
#(n,1). How to compute the sum of of the p matrix products at once? (result has
#shape (n,1))
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


In [320]:
#Consider a 16x16 array, how to get the block­sum (block size is 4x4)? 
import numpy as np
arra1 = np.ones((16,16))
k = 4
print("Original arrays:")
print(arra1)
result = np.add.reduceat(np.add.reduceat(arra1, np.arange(0, arra1.shape[0], k), axis=0),
                                      np.arange(0, arra1.shape[1], k), axis=1)
print("\nBlock-sum (4x4) of the said array:")
print(result)

Original arrays:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Block-sum (4x4) of the said array:
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [321]:
# How to implement the Game of Life using numpy arrays?
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
        Z[1:-1,0:-2] + Z[1:-1,2:] +
        Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)

In [322]:
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [323]:
#How to get the n largest values of an array 
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [324]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


In [326]:
#Given an arbitrary number of vectors, build the cartesian product (every
#combinations of every item)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [328]:
#How to create a record array from a regular array? 
Z = np.array([("Hello", 4.99, 13),
            ("World", 30.45, 40)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

In [329]:
print(R)

[(b'Hello',  4.99, 13) (b'World', 30.45, 40)]


In [333]:
# Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that
#contain elements of each row of B regardless of the order of the elements in B?
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)




[0 2 3 4 6 7]


In [334]:
#Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 2 4]
 [0 0 2]
 [1 3 2]
 [2 2 4]
 [1 2 0]
 [4 1 1]
 [3 1 0]
 [1 3 2]
 [3 4 2]
 [1 1 1]]
[[1 2 4]
 [0 0 2]
 [1 3 2]
 [2 2 4]
 [1 2 0]
 [4 1 1]
 [3 1 0]
 [1 3 2]
 [3 4 2]]


In [336]:
#Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
# Author: Daniel T. McDonald
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [337]:
#Given a two dimensional array, how to extract unique rows?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 1]
 [0 1 1]
 [1 0 0]]


In [340]:
# Considering a path described by two vectors (X,Y), how to sample it using
#equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x) # integrate path
y_int = np.interp(r_int, r, y)


In [341]:
print(x)

[  0.           0.09950042   0.19601332   0.28660095   0.3684244
   0.43879128   0.49520137   0.53538953   0.55736537   0.55944897
   0.54030231   0.49895573   0.43482931   0.34774848   0.237954
   0.1061058   -0.04671924  -0.21903564  -0.40896377  -0.61425018
  -0.83229367  -1.06017682  -1.29470246  -1.53243485  -1.76974492
  -2.00285904  -2.22791076  -2.44099478  -2.63822255  -2.81577868
  -2.96997749  -3.09731897  -3.19454328  -3.25868324  -3.28711385
  -3.27759841  -3.2283303   -3.13797012  -3.00567731  -2.83113599
  -2.61457448  -2.35677818  -2.05909545  -1.72343644  -1.35226463
  -0.9485811   -0.51590162  -0.05822672   0.41999512   0.91391061
   1.41831093   1.92768649   2.43628669   2.93818398   3.42734153
   3.89768376   4.34316892   4.75786287   5.1360132    5.47212274
   5.76102172   5.99793747   6.178561     6.29910941   6.35638348
   6.34781957   6.27153511   6.12636709   5.91190293   5.62850319
   5.27731578   4.86028133   4.38012946   3.84036588   3.24525022
   2.59976488

In [342]:
print(y)

[ 0.00000000e+00  9.98334166e-03  3.97338662e-02  8.86560620e-02
  1.55767337e-01  2.39712769e-01  3.38785484e-01  4.50952381e-01
  5.73884873e-01  7.04994219e-01  8.41470985e-01  9.80328096e-01
  1.11844690e+00  1.25262564e+00  1.37962962e+00  1.49624248e+00
  1.59931776e+00  1.68583018e+00  1.75292574e+00  1.79797017e+00
  1.81859485e+00  1.81273967e+00  1.77869209e+00  1.71512199e+00
  1.62111163e+00  1.49618036e+00  1.34030357e+00  1.15392568e+00
  9.37966820e-01  6.93823055e-01  4.23360024e-01  1.28900054e-01
 -1.86797259e-01 -5.20560791e-01 -8.68839747e-01 -1.22774130e+00
 -1.59307360e+00 -1.96039372e+00 -2.32505999e+00 -2.68228802e+00
 -3.02720998e+00 -3.35493616e+00 -3.66061824e+00 -3.93951353e+00
 -4.18704913e+00 -4.39888553e+00 -4.57097862e+00 -4.69963931e+00
 -4.78159012e+00 -4.81401780e+00 -4.79462137e+00 -4.72165488e+00
 -4.59396421e+00 -4.41101744e+00 -4.17292823e+00 -3.88047179e+00
 -3.53509317e+00 -3.13890759e+00 -2.69469264e+00 -2.20587232e+00
 -1.67649299e+00 -1.11119

In [343]:
#. Given an integer n and a 2D array X, select from X the rows which can be
#interpreted as draws from a multinomial distribution with n degrees, i.e., the rows
#which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]
