# Numpy

In [1]:
import numpy as np

# Array

In [3]:
np.array([10,45.55,26.67,7,9,500,2987.356])

array([  10.   ,   45.55 ,   26.67 ,    7.   ,    9.   ,  500.   ,
       2987.356])

In [4]:
arr = np.array([1,2,3.5,6.4,50,100,124.66,199.22])

In [5]:
arr

array([  1.  ,   2.  ,   3.5 ,   6.4 ,  50.  , 100.  , 124.66, 199.22])

In [6]:
np.array([10,45.55,26.67,7,9,500,2987.356,45,'78.7','BCD'])

array(['10', '45.55', '26.67', '7', '9', '500', '2987.356', '45', '78.7',
       'BCD'], dtype='<U32')

In [7]:
arr

array([  1.  ,   2.  ,   3.5 ,   6.4 ,  50.  , 100.  , 124.66, 199.22])

In [8]:
arr[3]

6.4

In [9]:
arr[2:5]

array([ 3.5,  6.4, 50. ])

In [10]:
np.array([10,20,30.5,45,56.23,99.5,100],dtype=float)

array([ 10.  ,  20.  ,  30.5 ,  45.  ,  56.23,  99.5 , 100.  ])

In [11]:
np.array([2,2.45,3,3,87,3.92,4,5.66,7],ndmin=4)

array([[[[ 2.  ,  2.45,  3.  ,  3.  , 87.  ,  3.92,  4.  ,  5.66,
           7.  ]]]])

In [12]:
arr = np.array([1,2,3.5,6.4,50,100,124.66,199.22,667.78,772],ndmin=3)

In [13]:
arr

array([[[  1.  ,   2.  ,   3.5 ,   6.4 ,  50.  , 100.  , 124.66, 199.22,
         667.78, 772.  ]]])

In [15]:
arr.ndim

3

In [16]:
l = [1,3,4,5,7,9,13,25,45,66.7,78,86.24]
arr = np.array(l)
arr

array([ 1.  ,  3.  ,  4.  ,  5.  ,  7.  ,  9.  , 13.  , 25.  , 45.  ,
       66.7 , 78.  , 86.24])

In [17]:
lst_cvrt_arr = np.asarray(l)
lst_cvrt_arr

array([ 1.  ,  3.  ,  4.  ,  5.  ,  7.  ,  9.  , 13.  , 25.  , 45.  ,
       66.7 , 78.  , 86.24])

In [18]:
arr.cumsum()

array([  1.  ,   4.  ,   8.  ,  13.  ,  20.  ,  29.  ,  42.  ,  67.  ,
       112.  , 178.7 , 256.7 , 342.94])

In [19]:
arr.argmax()

11

In [20]:
arr.argmin()

0

In [21]:
arr.dtype

dtype('float64')

In [22]:
arr.max()

86.24

In [23]:
arr.min()

1.0

In [24]:
arr.mean()

28.578333333333333

In [25]:
arr = np.arange(0,45)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [27]:
np.arange(5,125)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124])

In [28]:
arr = np.arange(10,260,20)

In [29]:
arr

array([ 10,  30,  50,  70,  90, 110, 130, 150, 170, 190, 210, 230, 250])

In [36]:
arr = np.arange(0,85)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

In [40]:
arr.reshape(17,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84]])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

In [42]:
arr.resize(5,17)

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67],
       [68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84]])

# From Function

In [44]:
np.fromfunction(lambda i,j: i+j,(12,8))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [10., 11., 12., 13., 14., 15., 16., 17.],
       [11., 12., 13., 14., 15., 16., 17., 18.]])

In [46]:
np.fromfunction(lambda i,j: i*j,(10,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.],
       [ 0.,  5., 10., 15., 20.],
       [ 0.,  6., 12., 18., 24.],
       [ 0.,  7., 14., 21., 28.],
       [ 0.,  8., 16., 24., 32.],
       [ 0.,  9., 18., 27., 36.]])

In [47]:
np.fromfunction(lambda i,j: i/j,(12,6))

C:\Users\Rakib\AppData\Local\Temp/ipykernel_13284/1191897852.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j: i/j,(12,6))
C:\Users\Rakib\AppData\Local\Temp/ipykernel_13284/1191897852.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j: i/j,(12,6))


array([[        nan,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
         0.2       ],
       [        inf,  2.        ,  1.        ,  0.66666667,  0.5       ,
         0.4       ],
       [        inf,  3.        ,  1.5       ,  1.        ,  0.75      ,
         0.6       ],
       [        inf,  4.        ,  2.        ,  1.33333333,  1.        ,
         0.8       ],
       [        inf,  5.        ,  2.5       ,  1.66666667,  1.25      ,
         1.        ],
       [        inf,  6.        ,  3.        ,  2.        ,  1.5       ,
         1.2       ],
       [        inf,  7.        ,  3.5       ,  2.33333333,  1.75      ,
         1.4       ],
       [        inf,  8.        ,  4.        ,  2.66666667,  2.        ,
         1.6       ],
       [        inf,  9.        ,  4.5       ,  3.        ,  2.25      ,
         1.8       ],
       [        inf, 10.        ,  5.        ,  3.

In [48]:
np.fromfunction(lambda i,j: i-j,(8,5))

array([[ 0., -1., -2., -3., -4.],
       [ 1.,  0., -1., -2., -3.],
       [ 2.,  1.,  0., -1., -2.],
       [ 3.,  2.,  1.,  0., -1.],
       [ 4.,  3.,  2.,  1.,  0.],
       [ 5.,  4.,  3.,  2.,  1.],
       [ 6.,  5.,  4.,  3.,  2.],
       [ 7.,  6.,  5.,  4.,  3.]])

In [49]:
def func(i,j):
    return i**j

In [56]:
f = func(7,4)

In [57]:
f

2401

In [58]:
np.fromfunction(lambda i,j: i==j,(8,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [59]:
np.fromfunction(lambda i,j: i==j,(8,8))

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])

In [60]:
l = [i for i in range(25)]
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [61]:
np.fromiter(l,float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [63]:
np.fromstring("-9,-7,-4,-2,-1,0.12,1, 2.5,4.77,5,6,7.29", sep =",", dtype=float)

array([-9.  , -7.  , -4.  , -2.  , -1.  ,  0.12,  1.  ,  2.5 ,  4.77,
        5.  ,  6.  ,  7.29])

In [64]:
np.fromstring("-9,-7,-4,-2,-1,0.12,1, 2.5,4.77,5,6,7.29", sep =",", dtype=int)

C:\Users\Rakib\AppData\Local\Temp/ipykernel_13284/74301086.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("-9,-7,-4,-2,-1,0.12,1, 2.5,4.77,5,6,7.29", sep =",", dtype=int)


array([-9, -7, -4, -2, -1,  0])

# Zeros and Ones

In [66]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
np.zeros(10, dtype=int)+5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [68]:
np.zeros(10, dtype=int)%2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [69]:
np.zeros(10, dtype=int)-(-5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [70]:
np.zeros(10, dtype=int)-10

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [71]:
arr_z = np.zeros(15, dtype=int)

In [72]:
arr_z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
for i in arr_z:
    for j in range(30):
        print(i+j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [74]:
for i in range(30):
    for j in arr_z:
        print(i+j)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
22
22
22
22
22
22
22
22
22
22
22
22
22
22
22
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
25
25
25
25
25
25
25
25
2

In [75]:
for i in range(12):
    print(arr_z + i)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
[11 11 11 11 11 11 11 11 11 11 11 11 11 11 11]


In [76]:
i=1
for j in arr_z:
    print(j+i)
    i+=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [77]:
i=1
for j in arr_z:
    print(j+i)
    i+=3

1
4
7
10
13
16
19
22
25
28
31
34
37
40
43


In [78]:
arr_o = np.ones(20, dtype = int)

In [79]:
arr_o

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
for i in arr_o:
    for j in range(20):
        print(i+j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
1
2
3
4
5
6
7
8
9
10
11
12
13
1

In [81]:
for i in range(20):
    for j in arr_o:
        print(i+j)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
12
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
13
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
14
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
16
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
20
20
20
20
20
20
20
20
20
20
20
20
20
2

In [83]:
for i in range(22):
    print(arr_o + i)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
[8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8]
[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
[11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11]
[12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12]
[13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13 13]
[14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14 14]
[15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15 15]
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
[17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17 17]
[18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18 18]
[19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19 19]
[2

In [84]:
i=1
for j in arr_o:
    print(j+i)
    i+=1

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [86]:
i=1
for j in arr_o:
    print(j+i)
    i+=3

2
5
8
11
14
17
20
23
26
29
32
35
38
41
44
47
50
53
56
59


In [87]:
i=2
for j in arr_o:
    print(j+i)
    i+=3

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60


In [90]:
np.linspace(3,25,3)

array([ 3., 14., 25.])

In [89]:
np.linspace(1,25,5)

array([ 1.,  7., 13., 19., 25.])

In [94]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [97]:
np.ones((5,3,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

# Random

In [98]:
np.random.rand(20)

array([0.75207774, 0.10838875, 0.04229008, 0.66547019, 0.77081395,
       0.3778567 , 0.54593629, 0.02271041, 0.51301508, 0.81965032,
       0.56370263, 0.15446466, 0.584171  , 0.91697579, 0.17709593,
       0.23052276, 0.75159522, 0.42308696, 0.1329668 , 0.35245267])

In [99]:
np.random.rand(6,6)

array([[0.91436313, 0.03583564, 0.24148211, 0.31216997, 0.79497747,
        0.2995367 ],
       [0.13095369, 0.96920796, 0.1791892 , 0.62097766, 0.76544911,
        0.22269273],
       [0.22376044, 0.07588767, 0.59717155, 0.459301  , 0.04110993,
        0.37756227],
       [0.91631609, 0.98165464, 0.60174881, 0.79668773, 0.96002273,
        0.88501926],
       [0.60402592, 0.56657218, 0.5061046 , 0.816914  , 0.65579252,
        0.52366513],
       [0.01320965, 0.9721971 , 0.89859777, 0.26974783, 0.89874817,
        0.56229063]])

In [100]:
np.random.rand(3,7)

array([[0.64820499, 0.64062034, 0.1073887 , 0.49805195, 0.99152593,
        0.87981133, 0.83478915],
       [0.61768586, 0.82557129, 0.58658444, 0.78608513, 0.85080035,
        0.92389715, 0.88714699],
       [0.33651167, 0.00231434, 0.05721829, 0.80573703, 0.15361495,
        0.73477418, 0.67232128]])

In [101]:
np.random.rand(4,2)

array([[0.79586942, 0.93204889],
       [0.67710879, 0.78182324],
       [0.88435749, 0.19776641],
       [0.53659238, 0.15858173]])

In [102]:
np.random.rand(4,4)

array([[0.47056137, 0.26565732, 0.49540535, 0.0676583 ],
       [0.66046223, 0.24244339, 0.19496024, 0.30056535],
       [0.87483574, 0.02529643, 0.6552719 , 0.27922797],
       [0.76102763, 0.06475225, 0.54310051, 0.95874698]])

In [103]:
np.random.rand(3,3)

array([[0.08403688, 0.23655335, 0.26793942],
       [0.93167937, 0.25833005, 0.83930767],
       [0.91065144, 0.17426699, 0.29172832]])

In [104]:
np.random.randn(2,8)

array([[-0.79243804, -0.1626587 ,  0.40912438, -0.33439895, -2.07718926,
        -0.19302217,  1.90075965, -1.90124196],
       [-0.69566208,  0.17120744, -0.70466518, -0.16969813, -0.29573102,
         1.66950102,  1.44853744,  0.32216109]])

In [105]:
np.random.randn(6,5)

array([[-0.25341529, -0.28034464, -0.94297433,  0.9931772 , -0.22071162],
       [-0.50978625, -0.49749242, -1.38327469,  1.79070758, -1.07456458],
       [-0.42939683, -0.9892481 ,  1.80671917,  0.74336773,  0.35831048],
       [-0.04231481, -1.94019454,  0.05846208,  0.53381769,  1.80595325],
       [-0.15679415,  0.93422842,  0.30750587,  0.8954105 , -0.28159176],
       [-0.82320402,  0.41630253,  0.10089914, -2.1710076 , -1.3783033 ]])

In [106]:
np.random.randn(5,5)

array([[-1.38704155,  0.46265367,  1.85769198,  1.15361333,  0.31580752],
       [-0.80077804, -0.23254635, -2.12333514,  0.44545327,  2.49515703],
       [-0.35383   ,  0.29662846,  0.72363026, -1.32192015,  1.2617261 ],
       [-2.22884058, -0.32766914, -0.90145713, -0.52555782,  0.18929596],
       [-1.46799152,  1.32904567,  0.62320826, -1.33116079,  0.98185103]])

In [113]:
np.random.randint(4,1200)

987

In [114]:
np.random.randint(20,200,(7,8))

array([[ 99,  51, 143,  30,  42, 131, 167, 159],
       [ 79, 184, 181,  57, 154, 127, 156, 176],
       [126, 195, 100,  48,  22, 195, 160,  44],
       [ 24, 150, 111, 179,  87,  20,  50, 126],
       [104,  31,  42, 134,  44, 113, 122,  52],
       [ 61, 180, 174, 138,  29,  22,  66,  84],
       [ 64, 120, 135,  39,  88, 118,  25, 163]])

In [116]:
arr = np.random.randint(40,4000,(10,8))

In [117]:
arr

array([[ 301, 1264,  605, 3561, 2501, 1677, 1786,  439],
       [ 939, 2233, 3524, 1124, 1289, 2115, 1594,  225],
       [1071, 1794, 2926, 3507,  463, 2192, 2519, 3910],
       [3115, 1968, 1814, 1705, 2407, 2760,  677, 2702],
       [2942, 1900, 2091, 3424, 1178, 1204,  491,  458],
       [3944, 2428,   89, 1476, 1756, 2030, 2645,  881],
       [1553, 3523, 2244, 1068, 1429, 2486, 2391, 3773],
       [ 161, 3394, 3496,  890,  255,  546,  564, 2089],
       [1883, 2924, 3750, 1464, 3304, 2239, 1728, 2790],
       [1133, 3102, 1022, 3250,  746, 2016, 2822, 1620]])

# Stats and Math

In [118]:
arr[1]

array([ 939, 2233, 3524, 1124, 1289, 2115, 1594,  225])

In [120]:
np.sin(arr[1])

array([ 0.32990546,  0.62284714, -0.76236341, -0.63666827,  0.81167382,
       -0.65042523, -0.93650426, -0.93009488])

In [121]:
arr[3]

array([3115, 1968, 1814, 1705, 2407, 2760,  677, 2702])

In [122]:
np.cos(arr[3])

array([ 0.11065688,  0.20630526, -0.26649766, -0.63343584,  0.85769462,
       -0.11062692, -0.01321646,  0.97359387])

In [123]:
arr[8]

array([1883, 2924, 3750, 1464, 3304, 2239, 1728, 2790])

In [132]:
np.tan(arr[8])

array([ 2.46923125, -1.07766245, -1.79125814,  0.01782531, -1.41467854,
       -1.41494999,  0.12468063,  0.27215961])

In [133]:
np.pi

3.141592653589793

In [135]:
arr[6]

array([1553, 3523, 2244, 1068, 1429, 2486, 2391, 3773])

In [137]:
np.degrees(arr[6])

array([ 88980.34558382, 201853.03122459, 128571.72922736,  61191.89251997,
        81875.66892419, 142437.30786952, 136994.20881578, 216176.97610286])

In [139]:
arr[5]

array([3944, 2428,   89, 1476, 1756, 2030, 2645,  881])

In [140]:
np.percentile(arr[5], 60, axis=0)

2109.6

In [141]:
arr[4]

array([2942, 1900, 2091, 3424, 1178, 1204,  491,  458])

In [148]:
np.percentile(arr[4], 46, axis=0)

1357.1200000000001

In [149]:
arr[9]

array([1133, 3102, 1022, 3250,  746, 2016, 2822, 1620])

In [150]:
arr[9].mean()

1963.875

In [155]:
arr[0]

array([ 301, 1264,  605, 3561, 2501, 1677, 1786,  439])

In [156]:
np.mean(arr[0])

1516.75

In [153]:
arr[7]

array([ 161, 3394, 3496,  890,  255,  546,  564, 2089])

In [157]:
np.median(arr[7])

727.0

In [158]:
arr[2]

array([1071, 1794, 2926, 3507,  463, 2192, 2519, 3910])

In [160]:
arr[2].sort()

In [161]:
arr[2]

array([ 463, 1071, 1794, 2192, 2519, 2926, 3507, 3910])

In [162]:
arr[9]

array([1133, 3102, 1022, 3250,  746, 2016, 2822, 1620])

In [163]:
np.sort(arr[9])

array([ 746, 1022, 1133, 1620, 2016, 2822, 3102, 3250])

In [164]:
arr[6]

array([1553, 3523, 2244, 1068, 1429, 2486, 2391, 3773])

In [166]:
np.average(arr[6])

2308.375

In [167]:
arr[2]

array([ 463, 1071, 1794, 2192, 2519, 2926, 3507, 3910])

In [168]:
arr[2].std()

1097.8077871376208

In [169]:
arr[7]

array([ 161, 3394, 3496,  890,  255,  546,  564, 2089])

In [170]:
np.std(arr[7])

1292.9461451951508

In [171]:
arr[5]

array([3944, 2428,   89, 1476, 1756, 2030, 2645,  881])

In [172]:
arr[5].var()

1193367.359375

In [173]:
arr[0]

array([ 301, 1264,  605, 3561, 2501, 1677, 1786,  439])

In [174]:
np.var(arr[0])

1097580.6875

In [175]:
arr[4]

array([2942, 1900, 2091, 3424, 1178, 1204,  491,  458])

In [177]:
np.sqrt(arr[4])

array([54.24020649, 43.58898944, 45.72745346, 58.51495535, 34.3220046 ,
       34.69870315, 22.15851981, 21.40093456])

# Finish